# Generated by Django 4.2.7 on 2023-12-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_Name', models.CharField(max_length=30)),
                ('release_date', models.DateTimeField()),
                ('rate_album', models.CharField(choices=[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)], default=None, max_length=10)),
            ],
        ),
    ]
